name: generate animation

on:
  schedule:
    - cron: "0 0 * * *"  # todo dia à meia-noite
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: generate github-contribution-grid-snake.svg (normal)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: edersoncruz
          outputs: dist/github-contribution-grid-snake.svg

      - name: generate github-contribution-grid-snake-dark.svg (dark mode)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: edersoncruz
          outputs: dist/github-contribution-grid-snake-dark.svg
          palette: github-dark

      - name: push generated svgs to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
