name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: edersoncruz
          outputs: |
            ./github-contribution-grid-snake.svg

      - name: Commit and push the snake svg
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git clone --depth=1 --branch=output https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git output
          cp github-contribution-grid-snake.svg output/
          cd output
          git add .
          git commit -m "update contribution snake" || echo "No changes to commit"
          git push
